### ISSUE TITLE
[BUG] Identity beta model can not be serialized to json (using to_json() extension method)

### ISSUE THREAD

**Issue by ianphilm** [sailpoint-oss/python-sdk#14]
In attempting to convert the return value of a sailpoint.beta.IdentitiesApi.list_identities() call to a list of json objects, the identity.to_json() call fails with the below error:

> line 147, in main
>     test = [i.to_json() for i in identities]
>             ^^^^^^^^^^^
>   File "/Users/imckenzie/code/corporate-identity-engineering/.venv/lib/python3.12/site-packages/sailpoint/beta/models/identity.py", line 84, in to_json
>     return json.dumps(self.to_dict())
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 231, in dumps
>     return _default_encoder.encode(obj)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 200, in encode
>     chunks = self.iterencode(o, _one_shot=True)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 258, in iterencode
>     return _iterencode(o, 0)
>            ^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 180, in default
>     raise TypeError(f'Object of type {o.__class__.__name__} '
> TypeError: Object of type datetime is not JSON serializable

I'm unsure if this is expected / not really a bug, but it seems like the to_json() parsing logic would generally be able to handle datetime objects.

**Comment by tyler-mairose-sp** [comment]
@ianphilm You are correct, we had to change the way that `to_json` worked. This is fixed with https://github.com/sailpoint-oss/python-sdk/commit/51f04b29216a80bc58be3553940142fa3208165d and will be included in the next release. Thank you for bringing this to our attention!
