### ISSUE TITLE
[Bug] sailpoint.beta.IdentitiesApi.list_identities() Response Identity Object Contains mismatched Alias data

### ISSUE THREAD

**Issue by ianphilm** [sailpoint-oss/python-sdk#16]
Hello, I've realized in testing a script that uses sailpoint.beta.IdentitiesApi.list_identities() endpoint, that the returned identity.alias property is not matching what the Beta API returns (tested via Postman). It seems that the SDK is mapping that value to the authoritative source account.name of the identity, while the API seems to display the the SailPoint Username (uid).

**Comment by tyler-mairose-sp** [comment]
@ianphilm, Can you give more details around this? I can't reproduce it. Using the script below I get the same value for identity.alias from both postman and the SDK.

```python
from typing import List
import sailpoint.v3
import sailpoint.beta
import json
from sailpoint.configuration import Configuration
from pydantic import StrictStr

configuration: Configuration = None
data: str = None

configuration = Configuration()

with sailpoint.beta.ApiClient(configuration) as api_client:
    results = sailpoint.beta.IdentitiesApi(api_client).list_identities()
    str_camp = results[0].model_dump_json(by_alias=True)
    json_camp = json.loads(str_camp)
    print(f"Json: {json.dumps(json_camp, indent=2)}")
```

**Comment by ianphilm** [comment]
Hi @tyler-mairose-sp , thanks for looking into this. Unfortunately I didn't do a good enough job documenting the circumstances under which I first noted the error, and I am now also not able to reproduce it in my environment. I wonder if it was confusion with an entity that had multiple identities or something similar. Apologies for this, I'll revive the ticket if I notice again.
